baseURL = "https://takumi.tmfam.com/"
canonifyURLs = true
defaultContentLanguage = "ja"
hasCJKLanguage = true
languageCode = "ja-jp"
theme = "hugo-coder"
title = "Takumin Notes"

[params]
    author = "Takumi Takahashi"
    info = "DevOps Software Engineer"
    description = "Takumi Takahashi Personal Website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpeg"

    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

    # footercontent = "TODO"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    # custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/takumin/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/takumiiinn/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
