baseURL = "https://takumi.tmfam.com/"
canonifyURLs = true
defaultContentLanguage = "ja"
hasCJKLanguage = true
languageCode = "ja-jp"
theme = "hugo-coder"
title = "Takumin Notes"
enableEmoji = true
enableGitInfo = true
googleAnalytics = "UA-62539992-1"

[params]
    author = "Takumi Takahashi"
    info = "Embedded DevOps Software Engineer"
    description = "Takumi Takahashi Personal Website"
    keywords = "blog,developer,personal"
    avatarurl = "images/avatar.jpeg"

    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

    rtl = false
    math = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/takumin"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/takumiiinn"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/takumiiinn"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/takumiiinn/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Pages"
    weight = 1
    url = "/pages/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "Category"
    weight = 3
    url  = "/categories/"
[[menu.main]]
    name = "Tags"
    weight = 4
    url  = "/tags/"
